### ISSUE TITLE
[bug]: Polling stopped working

### ISSUE THREAD

**Issue by BatangTurun** [dvcol/synology-download#195] opened 2023-03-17 02:04 UTC
### Description

Since latest update the progress bars for download do not auto update, must click the refresh button to force update.

### Affected part

Which part of the application is impacted

- [x] General UI
- [ ] General Options/Settings
- [ ] Connection settings
- [ ] Task list
- [ ] Notification
- [ ] Pop-up
- [ ] Context-menu
- [ ] Content-script (inside the page)
- [ ] Overlay
- [ ] Downloads

**Comment by BatangTurun** [comment] 2023-03-17 14:04
Hi,

Microsoft Edge - Version 111.0.1661.41 (Official build) (64-bit)

Download Station (client for Synology NAS) – Version 2.2.0

Connection - HTTP

Cheers

**Comment by BatangTurun** [comment] 2023-03-17 14:06
DSM 6.2.4-25556 Update 6

**Comment by dvcol** [comment] 2023-03-18 00:30
Um odd, there is no known issue on this version for polling as of now. Maybe an issue occured when upating.

Could you do an export of your redux store ? You can generate it here :

![image](https://user-images.githubusercontent.com/17250935/226073351-51afec10-e864-46bf-b0c6-377c0f42cbfd.png)

You might want to censor/anonymise your credential data as login/password is stored in plain text currently (you will find those in `store.settings.connection`.

Also, if you haven't tried it yet, login-out then login back in, and disabling/re-enabling polling might restart the service.

**Comment by BatangTurun** [comment] 2023-03-18 02:23
Hi,

 

I had previously turned polling on and off as well as log out/in to see if that helped but it did not.

 

As mentioned only after updating to version 2.2.0 this issue started.

 

Included here is the Redux file with the appropriate redactions.

 

Note: The file is now formatted JSON.

 

Regards

 

David

**Comment by dvcol** [comment] 2023-03-18 09:51
Hello, please post the file directly on the github thread, payload are not forwarded by github email response :)

**Comment by BatangTurun** [comment] 2023-03-18 17:03
[synology_download_redux_snapshot_2023-03-18T00_44_24.595Z.zip](https://github.com/dvcol/synology-download/files/11009121/synology_download_redux_snapshot_2023-03-18T00_44_24.595Z.zip)

**Comment by dvcol** [comment] 2023-03-18 19:00
From what I see in the states, everything seems in order, the service is logged, polling is enabled, and polling rate is at default.

If you don't have any error logs in the extension or the popup, it might be that the polling service is stuck in a stopped state because of a corrupt update.

Can you try to clear your local and sync storage and then uninstall re-install the extension ?

![image](https://user-images.githubusercontent.com/17250935/226130505-aae704a3-d196-4b6b-825c-517b44a2dc6d.png)

With little luck it was just a fluke error (I pushed a lot of update in a short amount of time, it might had migration errors because of it).

**Comment by dvcol** [comment] 2023-03-18 23:37
Quick update, I found a bug with error handling that broke polling if an auth error when polling occured.

It should be fixed in the next [release](https://github.com/dvcol/synology-download/releases/tag/v2.2.1) (you might not need to clear/re-install if this is the cause of your issue).

Did you have an error when auto-polling tasks or statistics at one point before polling stopped working ?

**Comment by BatangTurun** [comment] 2023-03-19 04:31
I upgraded to Version 2.2.1 and now polling is working again.

Thanks for the help.

**Comment by dvcol** [comment] 2023-03-19 09:34
Awesome, I’m closing this issue then, thanks for reporting the bug and helping debugging !

if it ever comes back don’t hesitate to re-open an issue :)

Also if you are enjoying the extension, please leave a review in the [store](https://chrome.google.com/webstore/detail/download-station-client-f/ebbdkledlkjpgbbmmopgbnnjmklnkcef), it helps with discovery :)

**Closed by dvcol** 2023-03-19 09:34 UTC
Labels: bug, bug-report
