### ISSUE TITLE
[bug]: Auto login not working

### ISSUE THREAD

**Issue by tomasz90** [dvcol/synology-download#159] opened 2023-01-23 22:20 UTC
### Description

Auto loging not working, after some time I am forced to manually login. When user uses magnet link on newly opened chrome, user sees popup that he need to log in, despite autologin checkbox checked in settings.

### Affected part

Which part of the application is impacted

- [ ] General UI
- [ ] General Options/Settings
- [x] Connection settings
- [ ] Task list
- [ ] Notification
- [ ] Pop-up
- [ ] Context-menu
- [ ] Content-script (inside the page)
- [ ] Overlay

### Steps to Reproduce the Issue

1. Open chrome
2. Try to download any torent and use magnet link

### Versions

**Version: 1.14.6**: 1.14.6

**Browser version**: 109.0.5414.75

**DSM version**: 7.1.1-42962 Update 2

**Comment by dvcol** [comment] 2023-03-07 01:04
Some fixes for login behavior will be included in the next release.

This might solve it, but without being able to easily reproduce the issue it might be complicated to fix.

I'm closing this for now, but if the issue persist, please fell free to re-open with mode details.

Note that due to limitation with service worker access to unseure urls, if you are using https, you either need to install a valid certificate, or open the popup in between restart or extension update.

**Closed by dvcol** 2023-03-07 01:04 UTC
Labels: bug
