### ISSUE TITLE
[bug]: Failed to create download

### ISSUE THREAD

**Issue by omiazad** [dvcol/synology-download#206] opened 2023-04-02 16:56 UTC
### Affected part

Connection (login/fetching)

### Extension version

2.5.2

### DSM version

7.1.1-42962 Update 4

### Browser version

111.0.5563.147 (Official Build) (64-bit)

### Description

When I click on a magnet link, it cannot create download and shows this error -

![2023-04-02 22_47_45-Star Trek Nemesis 2002 REMASTERED BRRip x264-ION10 Torrent download - Opera](https://user-images.githubusercontent.com/3358147/229367319-da913f0f-5398-4af6-b8f8-1beecf065972.png)

The previous version worked like a charm, something is not right with this version. Please check.

### Steps to Reproduce the Issue

Just click on any magnet link.

### Screenshots or Mock up

![2023-04-02 22_47_45-Star Trek Nemesis 2002 REMASTERED BRRip x264-ION10 Torrent download - Opera](https://user-images.githubusercontent.com/3358147/229367373-cbd77b5b-467f-4629-96dd-84c1130d5db3.png)

**Comment by dvcol** [comment] 2023-04-02 20:39
Hello, can you double check the extension version ?

The maximum version available through the store should be `2.5.2` unless you downloaded an unreleased version directly from github ?

Could you double check your DSM version also please.

Could you also inspect the network error and copy the fetch request that fails in the developer tools ?

![image](https://user-images.githubusercontent.com/17250935/229377818-9f6bc57a-41e2-4847-bad4-47135df5c7bf.png)
![image](https://user-images.githubusercontent.com/17250935/229377855-6b59e373-5963-4bf8-aa2e-958f04827819.png)

**Comment by omiazad** [comment] 2023-04-03 06:42
Hi,
I have updated the version. You are correct, it is 2.5.2. The DSM version is fine -
![2023-04-03 12_39_50-surovi-nas - Synology DiskStation and 2 more pages - Personal - Microsoft​ Edge](https://user-images.githubusercontent.com/3358147/229430648-1ee06311-1432-489b-89b5-84be632059f5.png)

Sorry I could not produce the network error for you. My console do not look like yours. And have no clues where to look into -
![2023-04-03 12_41_28-DevTools - Opera](https://user-images.githubusercontent.com/3358147/229430919-94f36c5d-5c3f-477f-b3a4-08372f2f6e09.png)

**Comment by dvcol** [comment] 2023-04-03 09:45
Hey, it seems you're using opera, then to access the debugging tools you need to go the manage extension page:

![image](https://user-images.githubusercontent.com/17250935/229473374-25d4a59b-6c01-464b-80da-920a22efc6e5.png)

Then click on developper mode and service worker:

![image](https://user-images.githubusercontent.com/17250935/229473251-541ecc28-72b1-4196-b960-2fd0015abfcc.png)

Then when you click on a magnet link a call should appear in the network tab:

![image](https://user-images.githubusercontent.com/17250935/229473809-c2f07c07-0ae9-4174-8daa-68a36a44fabd.png)

Can you then please copy the request (copy as fetch) and the response ?

From the error message it looks like your synology client does not support the api call wich is odd since you're on 7.1.1 🤔 

Does this occur every time ?

Please try this page to see if you reproduce the issue: https://archlinux.org/download/

**Comment by omiazad** [comment] 2023-04-03 14:34
So this is what I did.
I opened Archlinux page then cleared the console. Then clicked on the Magnet link and here is the report -

`fetch("https://mydns:88/webapi/entry.cgi", {
  "headers": {
    "accept": "*/*",
    "accept-language": "en-GB,en;q=0.9,bn;q=0.8",
    "access-control-allow-origin": "*",
    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
    "credentials": "omit",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "none"
  },
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": "api=SYNO.DownloadStation2.Task&method=create&version=2&type=%22url%22&create_list=false&destination=%22%22&url=%5B%22magnet%3A%3Fxt%3Durn%3Abtih%3A6df99344a488592ba3f71ffaef964a1dbfe0c8ed%26dn%3Darchlinux-2023.04.01-x86_64.iso%22%5D&_sid=uHYHgF4W4vT5oZW_nXWFaJ1iR2O9xTtr",
  "method": "POST",
  "mode": "cors",
  "credentials": "include"
});`

**Comment by omiazad** [comment] 2023-04-03 14:37
I have tried 2 more things. Tried to use my Synology Router's download manager with the extension. Same problem. Also tried to install the latest version from GitHub. Got this error -
![2023-04-03 20_36_24-Extensions](https://user-images.githubusercontent.com/3358147/229542663-324bd421-9738-4bad-b781-9ba77180e8f3.png)

**Comment by dvcol** [comment] 2023-04-03 17:39
The error you're receiving with the latest version is normal it's because the content script running in the tabs is not the same version as the one the background is trying to reach, you can ignore it.

If the issue is compatibility with downloadstation API, you can try using an olf version wich uses the legacy API while I investigate the issue.

release [1.2.1](https://github.com/dvcol/synology-download/releases/tag/v1.24.1) should still be using the old API (but there might be a few bugs lurking)

**Comment by omiazad** [comment] 2023-04-03 17:41
This is on my NAS:
![2023-04-03 23_39_12-surovi-nas - Synology DiskStation and 3 more pages - Personal - Microsoft​ Edge](https://user-images.githubusercontent.com/3358147/229585737-2574e4a5-18b2-41fe-acb0-53ef77285910.png)

This is on my router:
![2023-04-03 23_37_36-idea 52 planet and 1 more page - Personal - Microsoft​ Edge](https://user-images.githubusercontent.com/3358147/229585774-0be95eaa-7be4-4437-bea6-ad0751c52d42.png)

Here is the error message:
`Failed to create download task
The requested version does not support the functionality
https://archlinux.org/download/`

Please note, it was working fine just in the old version. It stopped working as soon as the extension received update.

**Comment by dvcol** [comment] 2023-04-03 19:53
Hi, this is the error message form the popup right ?

I need the response from the request (the place where you got the fetch request):

![image](https://user-images.githubusercontent.com/17250935/229612958-d31c5b99-10da-49b5-9c00-5382a64929f6.png)


Did you try the old release to see if this is caused by the API upgrade ?

**Comment by dvcol** [comment] 2023-04-03 22:03
Could you also run this query in your console ?

It will ping your nas and return all API endoints version that it's supports 

```
fetch("https://diskstation:5001/webapi/query.cgi?api=SYNO.API.Info&method=query&version=2&query=ALL", {
  "referrer": "",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": null,
  "method": "GET",
  "mode": "cors",
});
```

You might want to change `https://diskstation:5001 `with your nas ip

**Comment by dvcol** [comment] 2023-04-09 15:33
Hey, without more info it will be difficult to further diagnose the issue, but hoepully the above mentioned fix did the trick.

As the new version is now available in the store, I'm closing this issue.

Feel free to re-open it or open a new one if the issue persists :)

**Closed by dvcol** 2023-04-09 15:33 UTC
Labels: bug, bug-report
